name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4.0.4
        with:
          node-version: '18.x'
      - run: npm ci
      - name: Run tests
        run: npm test

        continue-on-error: false
